# Generated by Django 4.2.1 on 2023-05-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': 'Перемещение', 'verbose_name_plural': 'Перемещения'},
        ),
    ]
